/**
 * Permission constants
 * These should match the backend permission names
 */
export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_READ: 'DASHBOARD_READ',
  
  // Staff Management
  STAFF_CREATE: 'STAFF_CREATE',
  STAFF_READ: 'STAFF_READ',
  STAFF_UPDATE: 'STAFF_UPDATE',
  STAFF_DELETE: 'STAFF_DELETE',
  
  // Customer Management
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_READ: 'CUSTOMER_READ',
  CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
  CUSTOMER_DELETE: 'CUSTOMER_DELETE',
  
  // Role Management
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_READ: 'ROLE_READ',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  
  // Permission Management
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_READ: 'PERMISSION_READ',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',
  
  // Movie Management
  MOVIE_CREATE: 'MOVIE_CREATE',
  MOVIE_READ: 'MOVIE_READ',
  MOVIE_UPDATE: 'MOVIE_UPDATE',
  MOVIE_DELETE: 'MOVIE_DELETE',

  // Review Management
  REVIEW_CREATE: 'REVIEW_CREATE',
  REVIEW_READ: 'REVIEW_READ',
  REVIEW_UPDATE: 'REVIEW_UPDATE',
  REVIEW_DELETE: 'REVIEW_DELETE',
  
  // Showtime Management
  SHOWTIME_CREATE: 'SHOWTIME_CREATE',
  SHOWTIME_READ: 'SHOWTIME_READ',
  SHOWTIME_UPDATE: 'SHOWTIME_UPDATE',
  SHOWTIME_DELETE: 'SHOWTIME_DELETE',
  


  // Cinemas Management
  CINEMAS_CREATE: 'THEATER_CREATE',
  CINEMAS_READ: 'THEATER_READ',
  CINEMAS_UPDATE: 'THEATER_UPDATE',
  CINEMAS_DELETE: 'THEATER_DELETE',
  
  // Room Management
  ROOM_CREATE: 'ROOM_CREATE',
  ROOM_READ: 'ROOM_READ',
  ROOM_UPDATE: 'ROOM_UPDATE',
  ROOM_DELETE: 'ROOM_DELETE',
  
  // Booking Management
  BOOKING_CREATE: 'BOOKING_CREATE',
  BOOKING_READ: 'BOOKING_READ',
  BOOKING_UPDATE: 'BOOKING_UPDATE',
  BOOKING_DELETE: 'BOOKING_DELETE',
  
  // Ticket Booking (for staff to book tickets for customers)
  TICKET_BOOKING_CREATE: 'TICKET_BOOKING_CREATE',
  TICKET_BOOKING_READ: 'TICKET_BOOKING_READ',
  TICKET_BOOKING_UPDATE: 'TICKET_BOOKING_UPDATE',
  TICKET_BOOKING_DELETE: 'TICKET_BOOKING_DELETE',
  
  // Ticket Management
  TICKET_CREATE: 'TICKET_CREATE',
  TICKET_READ: 'TICKET_READ',
  TICKET_UPDATE: 'TICKET_UPDATE',
  TICKET_DELETE: 'TICKET_DELETE',
  
  // Combo Management
  COMBO_CREATE: 'COMBO_CREATE',
  COMBO_READ: 'COMBO_READ',
  COMBO_UPDATE: 'COMBO_UPDATE',
  COMBO_DELETE: 'COMBO_DELETE',
  
  // Invoice Management
  INVOICE_CREATE: 'INVOICE_CREATE',
  INVOICE_READ: 'INVOICE_READ',
  INVOICE_UPDATE: 'INVOICE_UPDATE',
  INVOICE_DELETE: 'INVOICE_DELETE',
  
  // Report Management
  REPORT_READ: 'REPORT_READ',
  REPORT_EXPORT: 'REPORT_EXPORT',
  
  // System Configuration
  SYSTEM_CREATE: 'SYSTEM_CREATE',
  SYSTEM_READ: 'SYSTEM_READ',
  SYSTEM_UPDATE: 'SYSTEM_UPDATE',
  SYSTEM_DELETE: 'SYSTEM_DELETE',

  // Work Schedule Management
  WORK_SCHEDULE_CREATE: 'WORK_SCHEDULE_CREATE',
  WORK_SCHEDULE_READ: 'WORK_SCHEDULE_READ',
  WORK_SCHEDULE_DELETE: 'WORK_SCHEDULE_DELETE',

  // Equipment Management
  EQUIPMENT_CREATE: 'EQUIPMENT_CREATE',
  EQUIPMENT_READ: 'EQUIPMENT_READ',
  EQUIPMENT_UPDATE: 'EQUIPMENT_UPDATE',
  EQUIPMENT_DELETE: 'EQUIPMENT_DELETE',

  // Price Config Management
  PRICE_CONFIG_CREATE: 'PRICE_CONFIG_CREATE',
  PRICE_CONFIG_READ: 'PRICE_CONFIG_READ',
  PRICE_CONFIG_UPDATE: 'PRICE_CONFIG_UPDATE',
  PRICE_CONFIG_DELETE: 'PRICE_CONFIG_DELETE',
} as const;

export type PermissionType = typeof PERMISSIONS[keyof typeof PERMISSIONS];


