import { getRoutePath } from "@/config/app.config";

// Route paths constants (relative paths without base)
const ROUTE_PATHS = {
  HOME: "",
  LOGIN: "login",
  DASHBOARD: "dashboard",
  MOVIES: "movies",
  CINEMAS: "cinemas",
  ROOMS: "rooms",
  ROOMS_CREATE: "rooms/create",
  ROOMS_EDIT: "rooms/edit/:id",
  CUSTOMERS: "customers",
  STAFF: "staff",
  SHOWTIMES: "showtimes",
  BOOKINGS: "bookings",
  TICKET_BOOKING: "ticket-booking",
  TICKETS: "tickets",
  COMBOS: "combos",
  INVOICES: "invoices",
  REPORTS: "reports",
  ROLES: "settings/roles",
  PERMISSIONS: "settings/permissions",
  SETTINGS_PROFILE: "settings/profile",
  SETTINGS_NOTIFICATIONS: "settings/notifications",
  SETTINGS_SECURITY: "settings/security",
  FORBIDDEN: "forbidden",
} as const;

// Generate full routes with base path
export const ROUTES = {
  HOME: getRoutePath(ROUTE_PATHS.HOME),
  LOGIN: getRoutePath(ROUTE_PATHS.LOGIN),
  DASHBOARD: getRoutePath(ROUTE_PATHS.DASHBOARD),
  MOVIES: getRoutePath(ROUTE_PATHS.MOVIES),
  CINEMAS: getRoutePath(ROUTE_PATHS.CINEMAS),
  ROOMS: getRoutePath(ROUTE_PATHS.ROOMS),
  ROOMS_CREATE: getRoutePath(ROUTE_PATHS.ROOMS_CREATE),
  ROOMS_EDIT: getRoutePath(ROUTE_PATHS.ROOMS_EDIT),
  CUSTOMERS: getRoutePath(ROUTE_PATHS.CUSTOMERS),
  STAFF: getRoutePath(ROUTE_PATHS.STAFF),
  SHOWTIMES: getRoutePath(ROUTE_PATHS.SHOWTIMES),
  BOOKINGS: getRoutePath(ROUTE_PATHS.BOOKINGS),
  TICKET_BOOKING: getRoutePath(ROUTE_PATHS.TICKET_BOOKING),
  TICKETS: getRoutePath(ROUTE_PATHS.TICKETS),
  COMBOS: getRoutePath(ROUTE_PATHS.COMBOS),
  INVOICES: getRoutePath(ROUTE_PATHS.INVOICES),
  REPORTS: getRoutePath(ROUTE_PATHS.REPORTS),
  ROLES: getRoutePath(ROUTE_PATHS.ROLES),
  PERMISSIONS: getRoutePath(ROUTE_PATHS.PERMISSIONS),
  SETTINGS_PROFILE: getRoutePath(ROUTE_PATHS.SETTINGS_PROFILE),
  SETTINGS_NOTIFICATIONS: getRoutePath(ROUTE_PATHS.SETTINGS_NOTIFICATIONS),
  SETTINGS_SECURITY: getRoutePath(ROUTE_PATHS.SETTINGS_SECURITY),
  FORBIDDEN: getRoutePath(ROUTE_PATHS.FORBIDDEN),
} as const;
