import { getRoutePath } from "@/config/app.config";

// Route paths constants (relative paths without base)
const ROUTE_PATHS = {
  HOME: "",
  LOGIN: "login",
  FORGOT_PASSWORD: "forgot-password",
  DASHBOARD: "dashboard",
  MOVIES: "movies",
  MOVIES_CREATE: "movies/create",
  MOVIES_EDIT: "movies/edit/:id",
  CINEMAS: "cinemas",
  ROOMS: "rooms",
  ROOMS_CREATE: "rooms/create",
  ROOMS_EDIT: "rooms/edit/:id",
  CUSTOMERS: "customers",
  STAFF: "staff",
  SHOWTIMES: "showtimes",
  BOOKINGS: "bookings",
  TICKET_BOOKING: "ticket-booking",
  TICKETS: "tickets",
  WORK_SCHEDULES: "work-schedules",
  SHIFT_TYPES: "shift-types",
  EQUIPMENT: "equipment",
  COMBOS: "combos",
  INVOICES: "invoices",
  REPORTS: "reports",
  ROLES: "settings/roles",
  PERMISSIONS: "settings/permissions",
  SEAT_PRICES: "settings/seat-prices",
  SETTINGS_BUFFER: "settings/buffer",
  SETTINGS_PROFILE: "settings/profile",
  SETTINGS_NOTIFICATIONS: "settings/notifications",
  SETTINGS_SECURITY: "settings/security",
  FORBIDDEN: "forbidden",
  REVIEWS: "reviews",
  MEDIA: "media",
  CHATBOT_CONFIG: "chatbot/documents",
  NOTIFICATIONS: "notifications",
  NOTIFICATIONS_LIST: "notifications/list",
  NOTIFICATIONS_SEND: "notifications/send",
  NOTIFICATIONS_VIEW: "notifications/view/:id",
  NOTIFICATIONS_TEMPLATES: "notifications/templates",
  NOTIFICATIONS_TEMPLATE_ADD: "notifications/templates/add",
  NOTIFICATIONS_TEMPLATE_EDIT: "notifications/templates/edit/:id",
  NOTIFICATIONS_LOGS: "notifications/logs",
} as const;

// Generate full routes with base path
export const ROUTES = {
  HOME: getRoutePath(ROUTE_PATHS.HOME),
  LOGIN: getRoutePath(ROUTE_PATHS.LOGIN),
  FORGOT_PASSWORD: getRoutePath(ROUTE_PATHS.FORGOT_PASSWORD),
  DASHBOARD: getRoutePath(ROUTE_PATHS.DASHBOARD),
  MOVIES: getRoutePath(ROUTE_PATHS.MOVIES),
  MOVIES_CREATE: getRoutePath(ROUTE_PATHS.MOVIES_CREATE),
  MOVIES_EDIT: getRoutePath(ROUTE_PATHS.MOVIES_EDIT),
  CINEMAS: getRoutePath(ROUTE_PATHS.CINEMAS),
  ROOMS: getRoutePath(ROUTE_PATHS.ROOMS),
  ROOMS_CREATE: getRoutePath(ROUTE_PATHS.ROOMS_CREATE),
  ROOMS_EDIT: getRoutePath(ROUTE_PATHS.ROOMS_EDIT),
  CUSTOMERS: getRoutePath(ROUTE_PATHS.CUSTOMERS),
  STAFF: getRoutePath(ROUTE_PATHS.STAFF),
  SHOWTIMES: getRoutePath(ROUTE_PATHS.SHOWTIMES),
  EQUIPMENT: getRoutePath(ROUTE_PATHS.EQUIPMENT),
  BOOKINGS: getRoutePath(ROUTE_PATHS.BOOKINGS),
  TICKET_BOOKING: getRoutePath(ROUTE_PATHS.TICKET_BOOKING),
  TICKETS: getRoutePath(ROUTE_PATHS.TICKETS),
  WORK_SCHEDULES: getRoutePath(ROUTE_PATHS.WORK_SCHEDULES),
  SHIFT_TYPES: getRoutePath(ROUTE_PATHS.SHIFT_TYPES),
  COMBOS: getRoutePath(ROUTE_PATHS.COMBOS),
  INVOICES: getRoutePath(ROUTE_PATHS.INVOICES),
  REPORTS: getRoutePath(ROUTE_PATHS.REPORTS),
  ROLES: getRoutePath(ROUTE_PATHS.ROLES),
  PERMISSIONS: getRoutePath(ROUTE_PATHS.PERMISSIONS),
  SEAT_PRICES: getRoutePath(ROUTE_PATHS.SEAT_PRICES),
  SETTINGS_BUFFER: getRoutePath(ROUTE_PATHS.SETTINGS_BUFFER),
  SETTINGS_PROFILE: getRoutePath(ROUTE_PATHS.SETTINGS_PROFILE),
  SETTINGS_NOTIFICATIONS: getRoutePath(ROUTE_PATHS.SETTINGS_NOTIFICATIONS),
  SETTINGS_SECURITY: getRoutePath(ROUTE_PATHS.SETTINGS_SECURITY),
  FORBIDDEN: getRoutePath(ROUTE_PATHS.FORBIDDEN),
  REVIEWS: getRoutePath(ROUTE_PATHS.REVIEWS),
  MEDIA: getRoutePath(ROUTE_PATHS.MEDIA),
  CHATBOT_CONFIG: getRoutePath(ROUTE_PATHS.CHATBOT_CONFIG),
  NOTIFICATIONS: getRoutePath(ROUTE_PATHS.NOTIFICATIONS),
  NOTIFICATIONS_LIST: getRoutePath(ROUTE_PATHS.NOTIFICATIONS_LIST),
  NOTIFICATIONS_SEND: getRoutePath(ROUTE_PATHS.NOTIFICATIONS_SEND),
  NOTIFICATIONS_VIEW: getRoutePath(ROUTE_PATHS.NOTIFICATIONS_VIEW),
  NOTIFICATIONS_TEMPLATES: getRoutePath(ROUTE_PATHS.NOTIFICATIONS_TEMPLATES),
  NOTIFICATIONS_TEMPLATE_ADD: getRoutePath(ROUTE_PATHS.NOTIFICATIONS_TEMPLATE_ADD),
  NOTIFICATIONS_TEMPLATE_EDIT: getRoutePath(ROUTE_PATHS.NOTIFICATIONS_TEMPLATE_EDIT),
  NOTIFICATIONS_LOGS: getRoutePath(ROUTE_PATHS.NOTIFICATIONS_LOGS),
} as const;
