import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { RouteGuard } from "@/components/route-guard";
import { ProtectedRouteNotification } from "@/components/protected-route-notification";
import { StoreInitializer } from "@/components/store-initializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <StoreInitializer>
            <RouteGuard>
              <Header />
              <ProtectedRouteNotification />
              {children}
              <Footer />
            </RouteGuard>
          </StoreInitializer>
        </ThemeProvider>
      </body>
    </html>
  );
}
